### ISSUE TITLE
UI tests are broken

### ISSUE THREAD

**Issue by gslevinkov** [tkey/tkey-android#16]
### Steps to reproduce 
1. Clone tkey-android repository
2. Sync and build without any additional steps
3. Launch `tkeyThresholdKeyTest` test class.

### Expected: 
All tests are green

### Actual:
All tests fail, with different errors and thread locks:
```
09-01 14:06:35.402 17399 17420 W System.err: Caused by: RuntimeError{code=1000}
09-01 14:06:35.402 17399 17420 W System.err: 	at com.web3auth.tkey.ThresholdKey.ThresholdKey.initialize(ThresholdKey.java:180)

java.lang.AssertionError: Could not initialize tkey
at org.junit.Assert.fail(Assert.java:89)
at com.web3auth.tkey.tkeyThresholdKeyTest.lambda$basic_threshold_key_reconstruct$0(tkeyThresholdKeyTest.java:52)
at com.web3auth.tkey.tkeyThresholdKeyTest$$ExternalSyntheticLambda1.onComplete(Unknown Source:2)
at com.web3auth.tkey.ThresholdKey.ThresholdKey.lambda$initialize$0$com-web3auth-tkey-ThresholdKey-ThresholdKey(ThresholdKey.java:146)
at com.web3auth.tkey.ThresholdKey.ThresholdKey$$ExternalSyntheticLambda11.run(Unknown Source:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
```

**Comment by metalurgical** [comment]
The are only Instrumentation tests, no UI tests.


![Screenshot 2023-09-06 at 10 54 50](https://github.com/tkey/tkey-android/assets/97008724/9f1cb83a-a03a-4705-b899-53696aba1193)

![Screenshot 2023-09-06 at 10 43 05](https://github.com/tkey/tkey-android/assets/97008724/323a0054-2d6b-4ab9-b9af-8a527bc60f34)

I don't get the same results you do, however it is possible that there may be a flaky test.

Is this for every attempt? Or intermittent?

**Comment by gslevinkov** [comment]
Checked again, this error is thrown when i have bad internet connection
sorry for the trouble 

p.s. but i think it would be better if get correct error message instead of just 1000
